import { normalize } from '../utils/util';

export const COLORS = {
  primary: '#EB9B1E',
  secondary: '#A1A1BC',
  primaryDark: '#E39200',
  primaryLight: '#FEF6E6',
  accent: '#EB9B1E',
  lightAccent: '#66C7BF',
  light: '#F5F7F8',
  white: '#FFFFFF',
  background: '#E3F2FD',
  transparent: 'rgba(255, 255, 255, 0.3)',
  darkText: '#333333',
  black: '#000000',
  eerieBlack: '#1F1F39',
  textPrimary: '#1B1A57',
  textSecondary: '#4F5E7B',
  heading: '#505050',
  red: '#D81B1B',
  label: '#A1A1A1',
  border: '#FDFDFD',
  grey: '#939393',
  lightGrey: '#EDEDED',
  mediumGrey: '#C4C4C4',
  purple: '#440687',
  textPurple: '#9065BE',
  lightPurple: '#F4F3FD',
  lightAccentPurple: '#F8F2FF',
  brown: '#CDAF58',
  cyan: '#D0FFF1',
  lightAccentCyan: '#F3FBFF',
  green: '#4CE417',
  darkGreen: '#1A2B26',
  orange: '#FF6B00',
};

export const FONTS = {
  regular: 'Poppins-Regular',
  medium: 'Poppins-Medium',
  bold: 'Poppins-Bold',
  extraBold: 'Poppins-ExtraBold',
  extraLight: 'Poppins-ExtraLight',
  light: 'Poppins-Light',
  semiBold: 'Poppins-SemiBold',
  thin: 'Poppins-Thin',
};

export const FONT_SIZES = {
  XXSMALL: normalize(8),
  XSMALL: normalize(10),
  SMALL: normalize(12),
  REGULAR: normalize(14),
  MEDIUM: normalize(16),
  LARGE: normalize(18),
  MLARGE: normalize(22),
  XLARGE: normalize(28),
  XXLARGE: normalize(48),
};